language: php

env:
  global:
    - 'FTP_USER=mrdaa'
    - 'FTP_PASS=19041997april'

script:
  # script buat folder baru
 - "curl -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com -Q 'mkd public_html/'"

  # # script upload file *.php
  - "curl -T koneksi.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T input.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T simpan.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T index.html -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T laporan.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T style.css -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  addons:
    apt:
      update: true